module.exports = {
  caseType:'caseworker_approved_benefit_appeal',
  initialState:'appeal_intake',
  states:['appeal_intake','consent_recorded','evidence_verified','eligibility_observed','appeal_draft','caseworker_review','claimant_approved','send_queued','sent','send_failed','corrected','closed'],
  createRoles:['caseworker','supervisor'],
  assessmentRoles:['caseworker','reviewer','supervisor'],
  auditRoles:['supervisor','reviewer','auditor'],
  connectorRoles:['integration_operator','supervisor'],
  evidenceKinds:['denial_notice','claimant_consent','identity_receipt','benefit_system_snapshot','eligibility_policy','document_manifest','deadline_calculation','appeal_draft_digest','caseworker_review','claimant_approval','translation_accessibility_report','send_receipt','send_failure','correction_record','lifecycle_snapshot'],
  requiredSignals:['denialVersion','benefitSystemVersion','policyVersion','documentVersion','rightsStatus','consentStatus','identityStatus','deadlineStatus','evidenceCompleteness','translationStatus','accessibilityStatus'],
  professionalBoundary:'Eligibility and appeal outputs are informational drafts. Authorized caseworkers and claimants review them; the system makes no benefits or legal determination and sends nothing automatically.',
  connectors:[
    {name:'benefit_system',purpose:'read-only authoritative case and denial receipts'},
    {name:'identity',purpose:'verified identity receipts'},
    {name:'document_store',purpose:'encrypted document pointers and digests'},
    {name:'sms_voice',purpose:'consented delivery receipts only'},
    {name:'scheduling',purpose:'appointment version receipts'},
    {name:'partner_directory',purpose:'versioned service-resource records'},
    {name:'notification',purpose:'deadline and lifecycle delivery receipts'},
  ],
  transitions:[
    {from:'appeal_intake',action:'record_consent',to:'consent_recorded',roles:['caseworker'],requiresEvidence:true},
    {from:'consent_recorded',action:'verify_evidence',to:'evidence_verified',roles:['reviewer','caseworker'],requiresEvidence:true,dualControl:true},
    {from:'evidence_verified',action:'record_eligibility_observation',to:'eligibility_observed',roles:['caseworker'],requiresEvidence:true},
    {from:'eligibility_observed',action:'record_appeal_draft',to:'appeal_draft',roles:['caseworker'],requiresEvidence:true},
    {from:'appeal_draft',action:'submit_caseworker_review',to:'caseworker_review',roles:['reviewer','supervisor'],requiresEvidence:true,dualControl:true},
    {from:'caseworker_review',action:'record_claimant_approval',to:'claimant_approved',roles:['caseworker','supervisor'],requiresEvidence:true,dualControl:true},
    {from:'claimant_approved',action:'queue_send',to:'send_queued',roles:['supervisor'],requiresEvidence:true,dualControl:true},
    {from:'send_queued',action:'record_send',to:'sent',roles:['integration_operator'],requiresEvidence:true},
    {from:'send_queued',action:'record_send_failure',to:'send_failed',roles:['integration_operator'],requiresEvidence:true},
    {from:'send_failed',action:'record_correction',to:'corrected',roles:['caseworker','supervisor'],requiresEvidence:true},
    {from:'sent',action:'close_appeal',to:'closed',roles:['caseworker','supervisor'],requiresEvidence:true},
    {from:'corrected',action:'close_appeal',to:'closed',roles:['caseworker','supervisor'],requiresEvidence:true},
  ],
  acceptedFixture:{denialVersion:'d1',benefitSystemVersion:'b1',policyVersion:'p1',documentVersion:'docs1',rightsStatus:'verified',consentStatus:'verified',identityStatus:'verified',deadlineStatus:'open',evidenceCompleteness:0.98,translationStatus:'passed',accessibilityStatus:'passed'},
  rejectedFixture:{denialVersion:'d1',benefitSystemVersion:'b1',policyVersion:'p1',documentVersion:'docs1',rightsStatus:'verified',consentStatus:'missing',identityStatus:'verified',deadlineStatus:'open',evidenceCompleteness:0.98,translationStatus:'passed',accessibilityStatus:'passed'},
  readyDisposition:'caseworker_and_claimant_review_required',
  holdDisposition:'consent_deadline_or_evidence_hold',
  decisionField:'sendCommand',
  assess:(x)=>{const completeness=Number(x.evidenceCompleteness);const ready=x.rightsStatus==='verified'&&x.consentStatus==='verified'&&x.identityStatus==='verified'&&x.deadlineStatus==='open'&&completeness>=0.95&&x.translationStatus==='passed'&&x.accessibilityStatus==='passed';return{disposition:ready?'caseworker_and_claimant_review_required':'consent_deadline_or_evidence_hold',sendCommand:null,metrics:{evidenceCompleteness:completeness},versions:{denial:x.denialVersion,benefitSystem:x.benefitSystemVersion,documents:x.documentVersion}};},
};
